[theme]

# Primary accent for interactive elements
primaryColor = '#E45354'

# Background color for the main content area
backgroundColor = '#E45354'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFFFFF'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"